### ISSUE TITLE
mobile testing of all elements (especially FF / Safari on opening of sidebar) 

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/declaring-independence#23]

**Comment by JosephMcArthur** [comment]
Safari on ios really hates my fancy fast pages. Old section doesn't hide on click.

**Comment by JosephMcArthur** [comment]
@markmacgillivray there are a few UI bugs on browsers on the sidebar & on pages like this: https://declaring-independence.org/determining-if-your-journal-is-a-good-fit-for-open-access#tab-1 which have the tabs code we wrote on gchat a couple of months ago. 

It would be good to have these straightened out. Let me know what documentation of the bugs are helpful here, I think quick look will make it obvious though! 

Feel free to use OAB's browserstack for this.

**Comment by JosephMcArthur** [comment]
one particular bug: https://www.dropbox.com/s/4b32s8vbqsus56j/Screenshot%202018-06-08%2014.20.27.png?dl=0 which is rather annoying. See bottom left.

**Comment by markmacgillivray** [comment]
OK, I believe the above issues are fixed now, looks fine to me. Nothing other immediate problems stand out, are there any more you want me to look at?

**Comment by JosephMcArthur** [comment]
I'm still seeing issues with hiding/appearing of text on chrome + mac. Firefox seems to be fine.

**Comment by JosephMcArthur** [comment]
Also, it's not going to the top of pages on any browser I don't think

**Comment by JosephMcArthur** [comment]
and it's not working on firefox (when you go back, the old content isn't hidden). 

Mark, if it's a pain, we should consider reverting this to just a few normal pages and leaving the tab thing all together. It was nice, but not worth spending hours and hours on.

**Comment by markmacgillivray** [comment]
Recommended to switch the hidden page parts to just normal pages with normal link clicks from the buttons and nav, as discussed with Joe.

**Comment by JosephMcArthur** [comment]
done
